### ISSUE TITLE
冒昧的开个issue，求教electrom打包

### ISSUE THREAD

**Issue by simongfxu** [ppoffice/ppoffice.github.io#1]
实在找不到其他联系方式
想问下electron打包怎么压缩到最小
我在Mac下面打包有128M，源代码加起来没有zip的版本也就五六M
看你在这个issue下面说可以到44M是怎么搞的？
https://github.com/oldj/SwitchHosts/issues/78

还是说我直接用electron-builder就可以搞定，目前还没尝试。

**Comment by ppoffice** [comment]
@simongfxu 
你可以参照下https://github.com/ppoffice/Hozz/blob/master/gulpfile.js#L169这里面的两个函数。
其中使用UPX压缩体积减小最明显，但是在一些平台上可能会出问题，所以我同时还向用户提供了未压缩的程序。
